Exppattern
Qsgs-Fans/FreeKill pull request #144
Opened 2023-05-06 13:10 UTC by Mechanel

视为技添加frequency（为了显示限定技）
主动技canUse修复 (by @Ho-spair )
Exppattern添加子类别
增加体力上限相关的log

2023-05-07 15:23 UTC, Ho-spair requested changes

2023-05-07 15:23 UTC, Ho-spair commented on lua/core/exppattern.lua
> +  elseif key == "cardSubtype" then
建议改造一下将子类别的判断整合进类别判断，避免pattern匹配类型个数进一步增加

2023-05-07 15:23 UTC, Ho-spair commented on packages/standard/init.lua
> +    if target ~= player or player:getMark("_luoyi-turn") == 0 then
失去技能应该不会导致发动次数清零吧，建议测试一下，脱离hasSkill是对的。

2023-05-07 15:23 UTC, Ho-spair commented on lua/server/room.lua
> +    skillName = skillName
skillName重复，多加一个proposer，即移动的执行者。

2023-05-07 15:23 UTC, Ho-spair commented on lua/client/i18n/zh_CN.lua
> +  ["#HealMaxHP"] = "%from 加了 %arg 点体力上限",
该文件末尾缺少空行，未通过格式检查。

2023-05-07 16:05 UTC, Mechanel commented on lua/core/exppattern.lua
> +  elseif key == "cardSubtype" then
感觉好难（挠头），先revert了

2023-05-07 16:07 UTC, Mechanel commented on packages/standard/init.lua
> +    if target ~= player or player:getMark("_luoyi-turn") == 0 then
确实不会

2023-05-13 05:22 UTC, Ho-spair approved these changes

2023-05-13 05:23 UTC, merged