bugfix
Qsgs-Fans/FreeKill pull request #229
Opened 2023-07-19 07:54 UTC by YoumuKon

-修改了可以通过取消目标以跳过exclusive_targets的bug
-为需要无视描述的请求添加-tmp标签（……）
-修改描述

2023-07-27 17:30 UTC, Mechanel commented on lua/server/room.lua
> +  return room.settings.gameMode:countInFunc(room)
应为Fk.game_modes[room.settings.gameMode]:countInFunc(room)

2023-07-31 06:49 UTC, Notify-ctrl requested changes

2023-07-31 06:49 UTC, Notify-ctrl commented on lua/core/util.lua
> +Util.global_can_use = function(self, player, card)
Util里面的函数是全局的，都应该用大驼峰才是

2023-07-31 06:49 UTC, Notify-ctrl commented on lua/server/mark_enum.lua
> +---使用牌无次数限制，可带清除标记后缀（-tmp为请求专用）
没必要三根斜杠呀，两根能显示来着

2023-07-31 06:49 UTC, Notify-ctrl commented on lua/server/room.lua
> +function Room:AskForAddTarget(player, targets, num, can_minus, distance_limited, prompt, skillName, data)
Room的方法名为啥大写开头

2023-07-31 06:49 UTC, Notify-ctrl commented on lua/server/room.lua
> +---@param prompt string|null @ 观星框的标题(暂时雪藏)
我写两根横杠是为了不让插件出警告

2023-07-31 06:49 UTC, Notify-ctrl commented on packages/standard/init.lua
> +    return room.players >= 5
井号不要了？

2023-07-31 07:06 UTC, YoumuKon commented on lua/server/room.lua
> +---@param prompt string|null @ 观星框的标题(暂时雪藏)
主要是这里断掉的话下文都不会显示，得换个方法

2023-07-31 07:06 UTC, YoumuKon commented on lua/server/room.lua
> +---@param prompt string|null @ 观星框的标题(暂时雪藏)
> 我写两根横杠是为了不让插件出警告

主要是这里断掉的话下文都不会显示，得换个方法

2023-07-31 14:59 UTC, YoumuKon commented on lua/server/mark_enum.lua
> +---使用牌无次数限制，可带清除标记后缀（-tmp为请求专用）
两根并不能

2023-08-01 18:19 UTC, Notify-ctrl approved these changes

2023-08-01 18:19 UTC, merged